export const SECTION_REGISTRY = [
  {
    id: 'home',
    title: 'Home',
    category: 'Operations',
    description: 'Console landing and quick entry points',
    path: '/home',
    keywords: ['home', 'dashboard', 'landing'],
  },
  {
    id: 'commandCenter',
    title: 'Command Center',
    category: 'Operations',
    description: 'Execution cockpit and operational control',
    path: '/command-center',
    keywords: ['command', 'center', 'operations', 'execution'],
  },
  {
    id: 'projectBoard',
    title: 'Tasks',
    category: 'Operations',
    description: 'Task board and project tracking',
    path: '/project-board',
    keywords: ['tasks', 'project', 'board', 'kanban'],
  },
  {
    id: 'overview',
    title: 'Overview',
    category: 'Finance',
    description: 'Financial overview and high-level KPIs',
    path: '/overview',
    keywords: ['overview', 'finance', 'kpi', 'summary'],
  },
  {
    id: 'flows',
    title: 'Flows',
    category: 'Operations',
    description: 'User journeys and automation flows',
    path: '/flows',
    keywords: ['flows', 'journey', 'automation', 'funnel'],
  },
  {
    id: 'executive',
    title: 'Executive Suite',
    category: 'Finance',
    description: 'Executive-level views and summaries',
    path: '/executive',
    keywords: ['executive', 'suite', 'management', 'summary'],
  },
  {
    id: 'affiliate',
    title: 'Affiliate Hub',
    category: 'Sales',
    description: 'Affiliate analysis, payments, and cohorts',
    path: '/affiliate',
    keywords: ['affiliate', 'payments', 'cohort', 'analysis'],
  },
  {
    id: 'traderPointsSimulator',
    title: 'Trader Points',
    category: 'Analytics',
    description: 'Trader points simulation and scenario analysis',
    path: '/trader-points',
    keywords: ['trader', 'points', 'simulator'],
  },
  {
    id: 'profitableRanking',
    title: 'Profitable Ranking',
    category: 'Sales',
    description: 'Top traders by profitability',
    path: '/retention/profitable-ranking',
    keywords: ['ranking', 'profit', 'retention', 'traders'],
  },
  {
    id: 'salesAgentsMonitor',
    title: 'Sales Agents Monitor',
    category: 'Sales',
    description: 'Performance monitor for sales agents',
    path: '/retention/sales-agents-monitor',
    keywords: ['sales', 'agents', 'monitor', 'retention'],
  },
  {
    id: 'allTemplates',
    title: 'All templates',
    category: 'Sales',
    description: 'Dedicated section for all email templates',
    path: '/retention/email-master-template',
    keywords: ['sales', 'templates', 'email', 'all templates'],
  },
  {
    id: 'fraud',
    title: 'User Behavior',
    category: 'Analytics',
    description: 'Fraud and behavior monitoring dashboard',
    path: '/fraud',
    keywords: ['fraud', 'behavior', 'risk', 'anomaly'],
  },
  {
    id: 'orgChart',
    title: 'Org Chart',
    category: 'Operations',
    description: 'Company organization structure',
    path: '/org-chart',
    keywords: ['org', 'chart', 'organization', 'team'],
  },
  {
    id: 'supportUserCheck',
    title: 'User Check Tool',
    category: 'Support',
    description: 'Lookup client details for support',
    path: '/support/user-check',
    keywords: ['support', 'user', 'check', 'client', 'crm'],
  },
  {
    id: 'aiAssistant',
    title: 'AI Assistant',
    category: 'Support',
    description: 'Support assistant interface',
    path: '/support/ai-assistant',
    keywords: ['ai', 'assistant', 'support'],
  },
  {
    id: 'trustpilotGuide',
    title: 'Trustpilot Guide',
    category: 'Trustpilot',
    description: 'Trustpilot guidance and daily tracking',
    path: '/trustpilot-guide',
    keywords: ['trustpilot', 'reviews', 'guide'],
  },
  {
    id: 'creolabs',
    title: 'Creolabs',
    category: 'Creolabs',
    description: 'Creolabs Qlik dashboards and analytics',
    path: '/creolabs',
    keywords: ['creolabs', 'qlik', 'analytics'],
  },
  {
    id: 'creolabsClientLists',
    title: 'Client Lists (30d)',
    category: 'Creolabs',
    description: 'Recent Creolabs client registration lists',
    path: '/creolabs/client-lists',
    keywords: ['creolabs', 'client', 'lists', '30d'],
  },
  {
    id: 'creolabsDbLive',
    title: 'DB Live',
    category: 'Creolabs',
    description:
      'Live Creolabs database workspace for real-time ingestion analysis and table serving',
    path: '/creolabs/db-live',
    keywords: ['creolabs', 'db', 'live', 'database', 'ingestion', 'table'],
  },
  {
    id: 'creolabsReport',
    title: 'Creolabs Report',
    category: 'Creolabs',
    description: 'Dedicated workspace for report templates, jobs, polling status, and outputs',
    path: '/creolabs/report',
    keywords: ['creolabs', 'report', 'templates', 'jobs', 'polling', 'download'],
  },
  {
    id: 'creolabsTestEnvironment3',
    title: 'Test Environment 3.0',
    category: 'Creolabs',
    description: 'Execution roadmap workspace for Creolabs live database delivery and rollout',
    path: '/creolabs/test-environment-3-0',
    keywords: ['creolabs', 'test', 'environment', '3.0', 'roadmap', 'execution', 'plan'],
  },
  {
    id: 'boardReportMailStudio',
    title: 'Report Mail Studio',
    category: 'Board',
    description: 'Board-level report email composer',
    path: '/board/report-mail-studio',
    keywords: ['board', 'report', 'mail', 'studio', 'email', 'compose', 'weekly'],
  },
  {
    id: 'reportsHub',
    title: 'Reports Hub',
    category: 'Analytics',
    description: 'Central entry point for reports',
    path: '/reports',
    keywords: ['reports', 'hub', 'download'],
  },
  {
    id: 'acuity',
    title: 'Acuity Lab',
    category: 'Analytics',
    description: 'Acuity market analytics area',
    path: '/acuity',
    keywords: ['acuity', 'market', 'analytics'],
  },
  {
    id: 'upload',
    title: 'Upload Reports',
    category: 'Operations',
    description: 'Upload report files and refresh artifacts',
    path: '/upload',
    keywords: ['upload', 'reports', 'csv', 'import'],
  },
  {
    id: 'notion',
    title: 'Notion Board',
    category: 'Operations',
    description: 'Embedded Notion board',
    path: '/notion',
    keywords: ['notion', 'board', 'docs'],
  },
  {
    id: 'admin',
    title: 'Admin Panel',
    category: 'Admin',
    description: 'Administrative controls and tools',
    path: '/admin',
    keywords: ['admin', 'panel', 'settings'],
  },
  {
    id: 'adminPasswords',
    title: 'Access Management',
    category: 'Admin',
    description: 'User access and password management',
    path: '/admin/passwords',
    keywords: ['admin', 'passwords', 'access', 'users'],
  },
]
