// Single source of truth for the 5 execution stories used across the Execution Hub.

export const seedStories = () => [
  {
    id: 'story-growth-acq',
    epic: 'Acquisition',
    title: 'Growth Engine: Acquisition & Brand',
    owner: 'Marketing / Growth',
    progress: 0.28,
    risk: 'Medium',
    goal: 'Generate a predictable weekly flow of qualified first deposits.',
    kpis: [
      { label: 'Cost Per Acquisition (CPA)', current: '—', target: 'Defined' },
      { label: 'First Time Deposits (FTD)', current: '—', target: 'Defined' },
      { label: 'Qualified First Time Deposits (QFTD)', current: '—', target: 'Defined' },
    ],
    status: 'Executing',
    blockers: [
      'Tracking gaps: UTM + event mapping not complete',
      'No weekly baseline for CPA/FTD/QFTD by channel',
    ],
    decisions: [
      { text: 'Set CPA guardrail and weekly QFTD target.', owner: 'CEO / Finance' },
      { text: 'Choose top 2 acquisition channels for the next 30 days.', owner: 'Growth Lead' },
    ],
    tasks: [
      {
        id: 'task-growth-1',
        title: 'Launch tracking plan — UTM + core events',
        context: 'Success: 100% FTD/QFTD tracked; <2% missing UTMs',
        owner: 'Growth Ops',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-growth-2',
        title: 'Build acquisition dashboard — CPA/FTD/QFTD by channel',
        context: 'Success: daily refresh; 1 weekly exec snapshot',
        owner: 'BI',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-growth-3',
        title: 'Ship landing pages — 3 high-intent pages',
        context: 'Success: QFTD/page tracked; conversion tracked weekly',
        owner: 'Web',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-growth-4',
        title: 'Deploy paid tests — 10 ads + clear stop rules',
        context: 'Success: 10 ads live; winners picked by CPA + QFTD',
        owner: 'Paid',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-growth-5',
        title: 'Publish content calendar — 4 weeks scheduled',
        context: 'Success: 12 posts shipped; track FTD/QFTD lift',
        owner: 'Content',
        done: false,
        impact: 'Medium',
      },
    ],
  },
  {
    id: 'story-partners-ib',
    epic: 'Acquisition',
    title: 'Partners & IB: Commercial Ops Stack',
    owner: 'Partnerships / Sales Ops',
    progress: 0.18,
    risk: 'High',
    goal: 'Make partner onboarding and payouts fast, accurate, and auditable.',
    kpis: [
      { label: 'Active Introducing Brokers (AIB)', current: '—', target: 'Defined' },
      { label: 'Time to First Referred Deposit (TFRD)', current: '—', target: 'Defined' },
      { label: 'Payout Error Rate (PER)', current: '—', target: 'Defined' },
    ],
    status: 'Executing',
    blockers: [
      'Partner terms scattered across chats/files',
      'No single payout calculation reference',
    ],
    decisions: [
      { text: 'Approve partner report template + cadence.', owner: 'COO' },
      { text: 'Confirm multi-level IB model and qualification rules.', owner: 'Partnerships Lead' },
    ],
    tasks: [
      {
        id: 'task-partners-1',
        title: 'Ship partner onboarding flow — signup → approval pipeline',
        context: 'Success: onboarding time ≤ 48h; drop-off tracked',
        owner: 'Partnerships Ops',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-partners-2',
        title: 'Create partner portal — referral link + KPI view',
        context: 'Success: 90% partners self-serve links + stats',
        owner: 'BI',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-partners-3',
        title: 'Deploy payout calculator — rules + tiers',
        context: 'Success: calculator matches sample cases 100%',
        owner: 'Partnerships',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-partners-4',
        title: 'Release payout report — monthly CSV + ledger',
        context: 'Success: generated in <5 min; PER <0.5%',
        owner: 'Finance',
        done: false,
        impact: 'Medium',
      },
      {
        id: 'task-partners-5',
        title: 'Automate partner attribution — referral → client match',
        context: 'Success: <1% unmatched referrals; weekly audit',
        owner: 'Data',
        done: false,
        impact: 'High',
      },
    ],
  },
  {
    id: 'story-product-crm',
    epic: 'Platform',
    title: 'Client Experience: Product, CRM & Education',
    owner: 'Product / CRM',
    progress: 0.22,
    risk: 'Medium',
    goal: 'Increase activation and reduce support load with CRM flows and education.',
    kpis: [
      { label: 'Activation Rate (AR)', current: '—', target: 'Defined' },
      { label: 'Net Promoter Score (NPS)', current: '—', target: 'Defined' },
      { label: 'First Response Time (FRT)', current: '—', target: 'Defined' },
    ],
    status: 'Executing',
    blockers: [
      'CRM triggers not mapped to user lifecycle',
      'Education content not linked to activation steps',
    ],
    decisions: [
      { text: 'Define the 7-day onboarding steps and target AR.', owner: 'Product Lead' },
      { text: 'Choose the 3 CRM flows to ship first.', owner: 'COO / Growth' },
    ],
    tasks: [
      {
        id: 'task-product-1',
        title: 'Map client journey — 1-page funnel spec',
        context: 'Success: each step has metric + owner assigned',
        owner: 'Product',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-product-2',
        title: 'Build CRM lifecycle — 6 triggered message flows',
        context: 'Success: 90% triggers pass QA test accounts',
        owner: 'CRM',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-product-3',
        title: 'Launch onboarding emails — 7-day sequence',
        context: 'Success: open/click rates + AR tracked weekly',
        owner: 'CRM',
        done: false,
        impact: 'Medium',
      },
      {
        id: 'task-product-4',
        title: 'Publish education hub — 10 core lessons',
        context: 'Success: lesson completion tracked per user',
        owner: 'Content',
        done: false,
        impact: 'Medium',
      },
      {
        id: 'task-product-5',
        title: 'Create support macro pack — 20 canned replies',
        context: 'Success: 20 macros live; usage + FRT tracked weekly',
        owner: 'Support',
        done: false,
        impact: 'Medium',
      },
    ],
  },
  {
    id: 'story-retention-prop',
    epic: 'Retention',
    title: 'Prop & Retention: Reactivation + Payments Friction',
    owner: 'Growth / Risk',
    progress: 0.16,
    risk: 'High',
    goal: 'Recover inactive users and reduce deposit/withdrawal failures.',
    kpis: [
      { label: 'Net Deposits (ND)', current: '—', target: '—' },
      { label: 'Deposits (DEP)', current: '—', target: '—' },
      { label: 'Withdrawals (WD)', current: '—', target: '—' },
    ],
    status: 'Executing',
    blockers: ['Failed deposits not logged end-to-end', 'Withdrawal status unclear for clients'],
    decisions: [
      { text: 'Pick top 3 payment errors to fix first.', owner: 'COO' },
      { text: 'Set guardrails for fraud + compliance checks.', owner: 'Risk / Compliance' },
    ],
    tasks: [
      {
        id: 'task-retention-1',
        title: 'Define churn segments — inactive cohorts list',
        context: 'Success: cohorts exported weekly; RR tracked',
        owner: 'Growth',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-retention-2',
        title: 'Launch reactivation sequences — 3 campaigns',
        context: 'Success: 3 sequences live; RR tracked per cohort',
        owner: 'CRM',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-retention-3',
        title: 'Build payment failure log — error dashboard',
        context: 'Success: top 10 errors ranked by volume',
        owner: 'BI',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-retention-4',
        title: 'Fix top 3 payment blockers — patch + release notes',
        context: 'Success: PSR tracked daily; top-3 errors drop WoW',
        owner: 'Engineering',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-retention-5',
        title: 'Ship withdrawal status page — client-visible tracker',
        context: 'Success: status ticket volume tracked; drops WoW',
        owner: 'Product',
        done: false,
        impact: 'Medium',
      },
    ],
  },
  {
    id: 'story-ops-org',
    epic: 'Ops',
    title: 'Ops & Org: Platform Stability + Company Setup',
    owner: 'COO / Ops',
    progress: 0.24,
    risk: 'Medium',
    goal: 'Keep the platform reliable and the company operationally ready.',
    kpis: [
      { label: 'Service Uptime (SU)', current: '—', target: 'Defined' },
      { label: 'Mean Time to Recovery (MTTR)', current: '—', target: 'Defined' },
      { label: 'Support Ticket Backlog (STB)', current: '—', target: 'Defined' },
    ],
    status: 'Executing',
    blockers: [
      'No incident checklist used consistently',
      'Key operational accounts/docs not centralized',
    ],
    decisions: [
      { text: 'Confirm owners for on-call, releases, and incident comms.', owner: 'CEO / COO' },
      { text: 'Approve LP migration timeline and rollback plan.', owner: 'Ops Lead' },
    ],
    tasks: [
      {
        id: 'task-ops-1',
        title: 'Set up monitoring — uptime + error alerts',
        context: 'Success: alerts fire <2 min; channel connected',
        owner: 'Engineering',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-ops-2',
        title: 'Publish incident playbook — 1-page runbook',
        context: 'Success: MTTR process used in next incident',
        owner: 'Ops',
        done: false,
        impact: 'Medium',
      },
      {
        id: 'task-ops-3',
        title: 'Add release checklist — pre/post deploy steps',
        context: 'Success: 100% releases follow checklist for 4 weeks',
        owner: 'Engineering',
        done: false,
        impact: 'Medium',
      },
      {
        id: 'task-ops-4',
        title: 'Create admin audit log — key actions tracked',
        context: 'Success: 100% critical actions have user + time',
        owner: 'Engineering',
        done: false,
        impact: 'High',
      },
      {
        id: 'task-ops-5',
        title: 'Build weekly ops report — SLA + risks summary',
        context: 'Success: 1 report/week; STB trend visible',
        owner: 'Ops',
        done: false,
        impact: 'Medium',
      },
    ],
  },
]
